# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
platform:ios,'9.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'DBAudioSDKDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!

  # Pods for DBAudioSDKDemo
  
  pod 'DBAudioSDK', :path => '../../'
#pod 'DBAudioSDK/DBLongASRKit', :path => '../../'
#pod 'DBAudioSDK/DBShortASRKit', :path => '../../'

  pod 'IQKeyboardManager', '~> 6.5.6' #asr的Demo地方会使用到
#  pod 'DBCommonLib', '~> 2.2.5'
pod 'Masonry' , '1.1.0'
#  pod 'FrameAccessor' ##布局快速设置frame
  pod 'Toast', '~> 4.0.0'
#  pod 'DBLongTimeASRSDK', '~>1.0.1'
#  pod 'DBAudioSDK/DBLongASRKit', '~>1.0.4'
#  pod 'DBAudioSDK/DBShortASRKit', '~>1.0.4'
#  pod 'SocketRocket'
#  pod 'DoraemonKit/Core', '~> 3.0.4', :configurations => ['Debug'] #必选

  target 'DBAudioSDKDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DBAudioSDKDemoUITests' do
    # Pods for testing
  end

end
