# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
platform:ios,'9.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'DBAudioSDKDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!

  # Pods for DBAudioSDKDemo
  
  pod 'DBAudioSDK', :path => '../../'
  
  pod 'IQKeyboardManager', '~> 6.5.6'
#  pod 'DBCommonLib', '~> 2.2.5'
  pod 'Masonry'
#  pod 'FrameAccessor' ##布局快速设置frame
  pod 'Toast', '~> 4.0.0'
#  pod 'DBLongTimeASRSDK', '~>1.0.1'
#  pod 'DBAudioSDK/DBLongASRKit', '~>1.0.4'
#  pod 'DBAudioSDK/DBShortASRKit', '~>1.0.4'
  pod 'SocketRocket'

  target 'DBAudioSDKDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DBAudioSDKDemoUITests' do
    # Pods for testing
  end

end
