# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DBAudioSDKDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DBAudioSDKDemo
  
  pod 'DBAudioSDK/DBLongASRKit', :path => '../../'


  target 'DBAudioSDKDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DBAudioSDKDemoUITests' do
    # Pods for testing
  end

end
